projects:
  demo:
    description: demo
  argocd:
    description: argocd
    sourceRepos:
      - url: https://github.com/K8sExample/cluster-infra.git
    clusterResourceWhitelist:
      - group: '*'
        kind: Namespace

applications:
  hello-world:
    namespace: demo
  argocd:
    namespace: argocd
    gitUrl: https://github.com/K8sExample/cluster-infra.git
  namespaces:
    namespace: argocd
    gitUrl: https://github.com/K8sExample/cluster-infra.git
  app-of-apps:
    namespace: argocd
    gitUrl: https://github.com/K8sExample/cluster-infra.git

parameters:
  global.clusterName: "production"
