projects:
  demo:
    description: demo
    sourceRepos:
      - url: https://github.com/K8sExample/k8s-demo-configurations.git
  argocd:
    description: argocd
    sourceRepos:
      - url: git@github.com:K8sExample/cluster-infra.git
        sshPrivateKeySecret:
           name: git-ssh
           key: sshPrivateKey
    clusterResourceWhitelist:
      - group: '*'
        kind: Namespace

applications:
  hello-world:
    namespace: demo
    gitUrl: https://github.com/K8sExample/k8s-demo-configurations.git
  argocd:
    namespace: argocd
    gitUrl: https://github.com/K8sExample/cluster-infra.git
  namespaces:
    namespace: argocd
    gitUrl: https://github.com/K8sExample/cluster-infra.git
  app-of-apps:
    namespace: argocd
    gitUrl: https://github.com/K8sExample/cluster-infra.git

parameters:
  global.clusterName: "production"
