apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps

spec:
  source:

  project: {{ .Release.Namespace }}
  source:
    repoURL: https://github.com/K8sExample/cluster-infra.git
    targetRevision: HEAD
    path: app-of-apps

    helm:
      valueFiles:
      - values-global.yaml
      - values-{{ .Values.environment }}.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
