apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/instance: argocd
data:
  repositories: |
       - url: git@github.com:k8sexample/cluster-infra.git
         sshPrivateKeySecret:
            name: git-ssh
            key: sshPrivateKey
