apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Release.Namespace }}
spec:
  sourceRepos:
    - git@github.com:K8sExample/cluster-infra.git

  destinations:
  - namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
---
