{{- range $name, $proj :=  .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $name }}
spec:
  description: {{ $proj.description }}

  sourceRepos:
    {{- if $proj.sourceRepos }}
    {{- range $proj.sourceRepos }}
    - {{ .url -}}
    {{ end }}
    {{- else }}
    - git@github.com:k8sexample/k8s-{{ $name }}-configurations.git
    {{ end }}

  destinations:
  {{- range $proj.destination_namespaces }}
  - namespace: {{ . }}
    server: https://kubernetes.default.svc
  {{- end }}
  - namespace: {{ $name }}
    server: https://kubernetes.default.svc

  {{- if $proj.oidcGroups }}
  roles:
    - name: project_team_role
      description: "basic permission for okta group"
      policies:
      - "p, proj:{{ $name }}:project_team_role, applications, *, {{ $name }}/*, allow"
      groups:
{{ toYaml $proj.oidcGroups| indent 6 }}
  {{-  end }}

---
{{- end }}
