apiVersion: v2
name: argocd
type: application
version: 0.1.0

dependencies: # A list of the chart requirements (optional)
  - name: argo
    version: 0.9.8
    repository: https://argoproj.github.io/argo-helm
