apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/part-of: argocd
data:
  repositories: |
       - type: helm
         url: https://argoproj.github.io/argo-helm
         name: argo

{{- range $name, $proj :=  .Values.projects }}

{{- if $proj.sourceRepos }}
{{ toYaml $proj.sourceRepos | indent 7 }}

{{- else }}
       - url: git@github.com:k8sexample/k8s-{{ $name }}-configurations.git
         sshPrivateKeySecret:
          name: git-ssh
          key: sshPrivateKey
{{- end }}

{{- end }}
