---
# Source: argocd/templates/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/part-of: argocd
data:
  accounts.omer: apiKey, login
  accounts.readonly: apiKey, login
  users.anonymous.enabled: "true"
  admin.enabled: "false"

  repositories: |
    - url: https://github.com/omer/k8s-demo-configurations
    - type: helm
      url: https://argoproj.github.io/argo-helm
      name: argo
      usernameSecret:
        name: my-secret
        key: username
      passwordSecret:
        name: my-secret
        key: password
      caSecret:
        name: my-secret
        key: ca
      certSecret:
        name: my-secret
        key: cert
      keySecret:
        name: my-secret
        key: key

  repository.credentials: |
    - url: https://github.com/omer
      sshPrivateKeySecret:
        name: my-secret
        key: sshPrivateKey

  help.chatUrl: 'https://mycorp.slack.com/argo-cd'
  help.chatText: 'Chat now!'
